// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUG89uARzyvhvNHqpUn9R9vUy1KBN9upo',
    appId: '1:970828292379:web:a2de5e82b99c74881373be',
    messagingSenderId: '970828292379',
    projectId: 'foode-a120b',
    authDomain: 'foode-a120b.firebaseapp.com',
    storageBucket: 'foode-a120b.firebasestorage.app',
    measurementId: 'G-ZDE2RWV0VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJv5XeIoXCSqvQQ5fd3oERZew1uvjeR_o',
    appId: '1:970828292379:android:1afaf48fb2a1163b1373be',
    messagingSenderId: '970828292379',
    projectId: 'foode-a120b',
    storageBucket: 'foode-a120b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu5XHFOy7qdZrtubYnhvA9-KVI3ebCj3w',
    appId: '1:970828292379:ios:e89236e0247436ac1373be',
    messagingSenderId: '970828292379',
    projectId: 'foode-a120b',
    storageBucket: 'foode-a120b.firebasestorage.app',
    iosBundleId: 'com.example.foode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu5XHFOy7qdZrtubYnhvA9-KVI3ebCj3w',
    appId: '1:970828292379:ios:e89236e0247436ac1373be',
    messagingSenderId: '970828292379',
    projectId: 'foode-a120b',
    storageBucket: 'foode-a120b.firebasestorage.app',
    iosBundleId: 'com.example.foode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUG89uARzyvhvNHqpUn9R9vUy1KBN9upo',
    appId: '1:970828292379:web:9edb6a848a9416541373be',
    messagingSenderId: '970828292379',
    projectId: 'foode-a120b',
    authDomain: 'foode-a120b.firebaseapp.com',
    storageBucket: 'foode-a120b.firebasestorage.app',
    measurementId: 'G-P4RXRXKN70',
  );
}
